### ISSUE TITLE
Status LED

### ISSUE THREAD

**Issue by Mynasru** [EmilFlach/slimmer_dimmer_v2#1]
add:

```
status_led:
  pin:
    number: GPIO02
    inverted: True #Normally off
```

GPIO02 is connected to the build in blue LED of the ESP12F module
